### ISSUE TITLE
Link to the English manual is wrong

### ISSUE THREAD

**Issue by JustCarmen** [jpretired/jp-main-menu-manual#1]
Your link to the English manual isn't correct.

This link doesn't work: https://store.fenechty.com/product/webtrees-manual/

It should be: https://richard-underwood.com/product/webtrees-manual/

I remembered that I 'bought' a free copy a while ago. And it still available for free. So I guess you need to update your text.

**Comment by jpretired** [comment]
Thank you, Carmen.
The link is corrected in module latest version 2.1.3.
